//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Client {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Client() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Client", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key phrases.
        /// </summary>
        internal static string ABS_ArtKeyPhrases {
            get {
                return ResourceManager.GetString("ABS_ArtKeyPhrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add document.
        /// </summary>
        internal static string addDoc {
            get {
                return ResourceManager.GetString("addDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add element.
        /// </summary>
        internal static string addElement {
            get {
                return ResourceManager.GetString("addElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add fact.
        /// </summary>
        internal static string addFact {
            get {
                return ResourceManager.GetString("addFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add organization.
        /// </summary>
        internal static string addOrganization {
            get {
                return ResourceManager.GetString("addOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add person.
        /// </summary>
        internal static string addPerson {
            get {
                return ResourceManager.GetString("addPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search parameters.
        /// </summary>
        internal static string addSearchParam {
            get {
                return ResourceManager.GetString("addSearchParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add dashboard.
        /// </summary>
        internal static string addVitrin {
            get {
                return ResourceManager.GetString("addVitrin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All checks.
        /// </summary>
        internal static string AllChecks {
            get {
                return ResourceManager.GetString("AllChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All inquiries.
        /// </summary>
        internal static string AllInq {
            get {
                return ResourceManager.GetString("AllInq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytical Business Solutions.
        /// </summary>
        internal static string anbr {
            get {
                return ResourceManager.GetString("anbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectable databases.
        /// </summary>
        internal static string avaDatabase {
            get {
                return ResourceManager.GetString("avaDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectable projects.
        /// </summary>
        internal static string avaProjects {
            get {
                return ResourceManager.GetString("avaProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings! 
        ///&lt;br&gt;
        ///Please review an auto-generated Semantic Archive report attached.  
        ///&lt;br&gt;
        ///This archive contains the check report named «{0}» dated {1}
        ///.
        /// </summary>
        internal static string BackgroundThread_r13_EmailBody {
            get {
                return ResourceManager.GetString("BackgroundThread_r13_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check report named «{0}» dated {1}.
        /// </summary>
        internal static string BackgroundThread_r13_EmailTitle {
            get {
                return ResourceManager.GetString("BackgroundThread_r13_EmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///Chosen results are successfully prepared on the &quot;{1}&quot;.&lt;br&gt;
        ///You can download it by the link below.&lt;br&gt;
        ///&lt;a href=&quot;{0}&quot;&gt;Download archive&lt;/a&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string BackgroundThread_r13_MsgBody {
            get {
                return ResourceManager.GetString("BackgroundThread_r13_MsgBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///Chosen results are successfully prepared on the &quot;{1}&quot;.&lt;br&gt;
        ///You can download it by the link below.&lt;br&gt;
        ///&lt;a href=&quot;{0}&quot;&gt;Download archive&lt;/a&gt;
        ///&lt;br&gt;&lt;br&gt;The file was sent to the specified e-mail address&lt;/p&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string BackgroundThread_r13_MsgBodyEmail {
            get {
                return ResourceManager.GetString("BackgroundThread_r13_MsgBodyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive reports  is ready for downloading ({0}).
        /// </summary>
        internal static string BackgroundThread_r13_MsgTitle {
            get {
                return ResourceManager.GetString("BackgroundThread_r13_MsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robots have finished the task.
        /// </summary>
        internal static string BackgroundThread_RobotsFinished {
            get {
                return ResourceManager.GetString("BackgroundThread_RobotsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse properties.
        /// </summary>
        internal static string browseproperties {
            get {
                return ResourceManager.GetString("browseproperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string CartDefaultName {
            get {
                return ResourceManager.GetString("CartDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Database.
        /// </summary>
        internal static string ChangeDatabase {
            get {
                return ResourceManager.GetString("ChangeDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist.
        /// </summary>
        internal static string Checklist {
            get {
                return ResourceManager.GetString("Checklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На основе введенных данных обнаружено - &lt;span id=&apos;count&apos;&gt;0&lt;/span&gt; досье. Для повторного запуска проверки в рамках существующего объекта, выберете его , после чего перейдите к выбору источников..
        /// </summary>
        internal static string CheckNote {
            get {
                return ResourceManager.GetString("CheckNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check organization.
        /// </summary>
        internal static string CheckOrg {
            get {
                return ResourceManager.GetString("CheckOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check person.
        /// </summary>
        internal static string CheckPerson {
            get {
                return ResourceManager.GetString("CheckPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results of {0} on object &quot;{1}&quot;. Result: {2}.
        /// </summary>
        internal static string CheckResume_GeneratedTitle {
            get {
                return ResourceManager.GetString("CheckResume_GeneratedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotated note for &quot;{0}&quot;.
        /// </summary>
        internal static string CheckResume_GeneratedTitleForAnnotatedNote {
            get {
                return ResourceManager.GetString("CheckResume_GeneratedTitleForAnnotatedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of {0} on object &quot;{1}&quot;. State: {2}.
        /// </summary>
        internal static string CheckResume_GeneratedTitleForState {
            get {
                return ResourceManager.GetString("CheckResume_GeneratedTitleForState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check.
        /// </summary>
        internal static string CheckResume_ModuleTitleCheck {
            get {
                return ResourceManager.GetString("CheckResume_ModuleTitleCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request.
        /// </summary>
        internal static string CheckResume_ModuleTitleInquire {
            get {
                return ResourceManager.GetString("CheckResume_ModuleTitleInquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks.
        /// </summary>
        internal static string Checks {
            get {
                return ResourceManager.GetString("Checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check status.
        /// </summary>
        internal static string CheckStatus {
            get {
                return ResourceManager.GetString("CheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has a mark: &quot;{1}&quot;.
        /// </summary>
        internal static string Check_MarkRelationNameTemplate {
            get {
                return ResourceManager.GetString("Check_MarkRelationNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; as a &quot;{1}&quot; in the inquery &quot;{2}&quot;.
        /// </summary>
        internal static string Check_RoleRelationNameTemplate {
            get {
                return ResourceManager.GetString("Check_RoleRelationNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change status.
        /// </summary>
        internal static string ChSta {
            get {
                return ResourceManager.GetString("ChSta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        internal static string Clearall {
            get {
                return ResourceManager.GetString("Clearall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance check.
        /// </summary>
        internal static string ComplianceCheck {
            get {
                return ResourceManager.GetString("ComplianceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubrics.
        /// </summary>
        internal static string ContentCollection_Rubrics {
            get {
                return ResourceManager.GetString("ContentCollection_Rubrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts.
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string DataBase {
            get {
                return ResourceManager.GetString("DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is unknown.
        /// </summary>
        internal static string Dateofbirthunknown {
            get {
                return ResourceManager.GetString("Dateofbirthunknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string deleteItem {
            get {
                return ResourceManager.GetString("deleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter description.
        /// </summary>
        internal static string Descriptionofparameters {
            get {
                return ResourceManager.GetString("Descriptionofparameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string Docs {
            get {
                return ResourceManager.GetString("Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact autoselect &quot;{0}&quot;.
        /// </summary>
        internal static string Docs_AutoExtractJobNameTemplate {
            get {
                return ResourceManager.GetString("Docs_AutoExtractJobNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Docs_AutoExtractJobNameTempl_Finished {
            get {
                return ResourceManager.GetString("Docs_AutoExtractJobNameTempl_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexed.
        /// </summary>
        internal static string Docs_AutoExtractJobNameTempl_Indexed {
            get {
                return ResourceManager.GetString("Docs_AutoExtractJobNameTempl_Indexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string Docs_AutoExtractJobNameTempl_Processing {
            get {
                return ResourceManager.GetString("Docs_AutoExtractJobNameTempl_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitted by sentences.
        /// </summary>
        internal static string Docs_AutoExtractJobNameTempl_Splitted {
            get {
                return ResourceManager.GetString("Docs_AutoExtractJobNameTempl_Splitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Docs_AutoExtractJobNameTempl_Started {
            get {
                return ResourceManager.GetString("Docs_AutoExtractJobNameTempl_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string editItem {
            get {
                return ResourceManager.GetString("editItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact date of birth.
        /// </summary>
        internal static string exactdateofbirth {
            get {
                return ResourceManager.GetString("exactdateofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an documents digest started.
        ///It may take several minutes. When job wil be finished you will be notified.
        /// </summary>
        internal static string Export_GenerateDocsDigest {
            get {
                return ResourceManager.GetString("Export_GenerateDocsDigest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Documents digest generation has been finished. &lt;br&gt;You can download digest by &lt;a href=&apos;{0}&apos;&gt;this link&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        internal static string Export_GenerateDocsDigest_AlertBody {
            get {
                return ResourceManager.GetString("Export_GenerateDocsDigest_AlertBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents digest generation has been finished.
        /// </summary>
        internal static string Export_GenerateDocsDigest_AlertMsg {
            get {
                return ResourceManager.GetString("Export_GenerateDocsDigest_AlertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an facts digest started.
        ///It may take several minutes. When job wil be finished you will be notified.
        /// </summary>
        internal static string Export_GenerateFactDigest {
            get {
                return ResourceManager.GetString("Export_GenerateFactDigest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Facts digest generation has been finished. &lt;br&gt;You can download digest by &lt;a href=&apos;{0}&apos;&gt;this link&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        internal static string Export_GenerateFactDigest_AlertBody {
            get {
                return ResourceManager.GetString("Export_GenerateFactDigest_AlertBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facts digest generation has been finished.
        /// </summary>
        internal static string Export_GenerateFactDigest_AlertMsg {
            get {
                return ResourceManager.GetString("Export_GenerateFactDigest_AlertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There aren&apos;t any facts for selected entity. Digest couldn&apos;t be created.
        /// </summary>
        internal static string Export_GenerateFactDigest_NoFacts {
            get {
                return ResourceManager.GetString("Export_GenerateFactDigest_NoFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts.
        /// </summary>
        internal static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facts.
        /// </summary>
        internal static string Facts {
            get {
                return ResourceManager.GetString("Facts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by type.
        /// </summary>
        internal static string filerByТypes {
            get {
                return ResourceManager.GetString("filerByТypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by type.
        /// </summary>
        internal static string Filterbytype {
            get {
                return ResourceManager.GetString("Filterbytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fullscreen.
        /// </summary>
        internal static string fullScreen {
            get {
                return ResourceManager.GetString("fullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery images.
        /// </summary>
        internal static string g1i {
            get {
                return ResourceManager.GetString("g1i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to object.
        /// </summary>
        internal static string gotoobject {
            get {
                return ResourceManager.GetString("gotoobject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        internal static string graph {
            get {
                return ResourceManager.GetString("graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object browsing history.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import in progress.... You will be notified upon completion.
        /// </summary>
        internal static string ImportCheck_Message {
            get {
                return ResourceManager.GetString("ImportCheck_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information on the object.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source data the verification.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input date.
        /// </summary>
        internal static string inputdate {
            get {
                return ResourceManager.GetString("inputdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of inquiris.
        /// </summary>
        internal static string Inqlist {
            get {
                return ResourceManager.GetString("Inqlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry for organization.
        /// </summary>
        internal static string InqOrg {
            get {
                return ResourceManager.GetString("InqOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry for person.
        /// </summary>
        internal static string InqPerson {
            get {
                return ResourceManager.GetString("InqPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry.
        /// </summary>
        internal static string Inquiry {
            get {
                return ResourceManager.GetString("Inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string InquiryController_SAProject_CDate {
            get {
                return ResourceManager.GetString("InquiryController_SAProject_CDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check date.
        /// </summary>
        internal static string InquiryController_SAProject_CheckDate {
            get {
                return ResourceManager.GetString("InquiryController_SAProject_CheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executor.
        /// </summary>
        internal static string InquiryController_SAProject_Owner {
            get {
                return ResourceManager.GetString("InquiryController_SAProject_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string InquiryController_SAProject_ProjectCode {
            get {
                return ResourceManager.GetString("InquiryController_SAProject_ProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubric.
        /// </summary>
        internal static string InquiryController_SAProject_Rubrics {
            get {
                return ResourceManager.GetString("InquiryController_SAProject_Rubrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string InquiryController_SAProject_State {
            get {
                return ResourceManager.GetString("InquiryController_SAProject_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string InquiryController_SAProject_Status {
            get {
                return ResourceManager.GetString("InquiryController_SAProject_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string InquiryController_SAProject_Title {
            get {
                return ResourceManager.GetString("InquiryController_SAProject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string InterestObjController_CheckState_InWork {
            get {
                return ResourceManager.GetString("InterestObjController_CheckState_InWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        internal static string InterestObjController_LabelMark {
            get {
                return ResourceManager.GetString("InterestObjController_LabelMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string InterestObjController_LabelRoles {
            get {
                return ResourceManager.GetString("InterestObjController_LabelRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string InterestObjController_LabelTypeName {
            get {
                return ResourceManager.GetString("InterestObjController_LabelTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string logOff {
            get {
                return ResourceManager.GetString("logOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/en/logo.gif.
        /// </summary>
        internal static string LogoPath {
            get {
                return ResourceManager.GetString("LogoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest news.
        /// </summary>
        internal static string MainPage_News {
            get {
                return ResourceManager.GetString("MainPage_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All news.
        /// </summary>
        internal static string MainPage_ReadAllNews {
            get {
                return ResourceManager.GetString("MainPage_ReadAllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed.
        /// </summary>
        internal static string MBFResult_Completed {
            get {
                return ResourceManager.GetString("MBFResult_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created.
        /// </summary>
        internal static string MBFResult_Created {
            get {
                return ResourceManager.GetString("MBFResult_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to networking error.
        /// </summary>
        internal static string MBFResult_ErrorNet {
            get {
                return ResourceManager.GetString("MBFResult_ErrorNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processing error.
        /// </summary>
        internal static string MBFResult_ErrorProcessing {
            get {
                return ResourceManager.GetString("MBFResult_ErrorProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error on the side source.
        /// </summary>
        internal static string MBFResult_ErrorResource {
            get {
                return ResourceManager.GetString("MBFResult_ErrorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save result error.
        /// </summary>
        internal static string MBFResult_ErrorSaveResult {
            get {
                return ResourceManager.GetString("MBFResult_ErrorSaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found.
        /// </summary>
        internal static string MBFResult_Found {
            get {
                return ResourceManager.GetString("MBFResult_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general error.
        /// </summary>
        internal static string MBFResult_GeneralError {
            get {
                return ResourceManager.GetString("MBFResult_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in progress.
        /// </summary>
        internal static string MBFResult_InProgress {
            get {
                return ResourceManager.GetString("MBFResult_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid.
        /// </summary>
        internal static string MBFResult_Invalid {
            get {
                return ResourceManager.GetString("MBFResult_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not enough input data.
        /// </summary>
        internal static string MBFResult_NotenoughInputData {
            get {
                return ResourceManager.GetString("MBFResult_NotenoughInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found.
        /// </summary>
        internal static string MBFResult_NotFound_v01 {
            get {
                return ResourceManager.GetString("MBFResult_NotFound_v01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stopped.
        /// </summary>
        internal static string MBFResult_Stopped {
            get {
                return ResourceManager.GetString("MBFResult_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no answer from user.
        /// </summary>
        internal static string MBFResult_UserIgnoreAlert {
            get {
                return ResourceManager.GetString("MBFResult_UserIgnoreAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile control.
        /// </summary>
        internal static string MenageProfiles {
            get {
                return ResourceManager.GetString("MenageProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main modules.
        /// </summary>
        internal static string mm {
            get {
                return ResourceManager.GetString("mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View mode.
        /// </summary>
        internal static string ModeView {
            get {
                return ResourceManager.GetString("ModeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My checks.
        /// </summary>
        internal static string MyChecks {
            get {
                return ResourceManager.GetString("MyChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My dashboards.
        /// </summary>
        internal static string myDashboard {
            get {
                return ResourceManager.GetString("myDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My inquiries.
        /// </summary>
        internal static string MyInq {
            get {
                return ResourceManager.GetString("MyInq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data....
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        internal static string nameofcompany {
            get {
                return ResourceManager.GetString("nameofcompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Inquiry.
        /// </summary>
        internal static string NewInq {
            get {
                return ResourceManager.GetString("NewInq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in new window.
        /// </summary>
        internal static string newWindow {
            get {
                return ResourceManager.GetString("newWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object details.
        /// </summary>
        internal static string objectInformation {
            get {
                return ResourceManager.GetString("objectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects of inquiry.
        /// </summary>
        internal static string ObjectsInquiry {
            get {
                return ResourceManager.GetString("ObjectsInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document original.
        /// </summary>
        internal static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online support.
        /// </summary>
        internal static string os {
            get {
                return ResourceManager.GetString("os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        internal static string passport {
            get {
                return ResourceManager.GetString("passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        internal static string patronymic {
            get {
                return ResourceManager.GetString("patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous checks.
        /// </summary>
        internal static string Pchecks {
            get {
                return ResourceManager.GetString("Pchecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase.
        /// </summary>
        internal static string Phrase {
            get {
                return ResourceManager.GetString("Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view.
        /// </summary>
        internal static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous surname.
        /// </summary>
        internal static string Previousname {
            get {
                return ResourceManager.GetString("Previousname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product list.
        /// </summary>
        internal static string productsList {
            get {
                return ResourceManager.GetString("productsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string properties {
            get {
                return ResourceManager.GetString("properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resfresh.
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facts Report.
        /// </summary>
        internal static string repOrganizationFactsByChapter {
            get {
                return ResourceManager.GetString("repOrganizationFactsByChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Report.
        /// </summary>
        internal static string repOrganizationOnlineDataByChapter {
            get {
                return ResourceManager.GetString("repOrganizationOnlineDataByChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an archive of reports started.
        ///It may take several minutes. When job wil be finished you will be notified.
        /// </summary>
        internal static string Report_UploadReportsArchived {
            get {
                return ResourceManager.GetString("Report_UploadReportsArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive reports creating process has been started. After that it will be sent by email
        ///It may take several minutes. When job wil be finished you will be notified.
        /// </summary>
        internal static string Report_UploadReportsArchived_0 {
            get {
                return ResourceManager.GetString("Report_UploadReportsArchived_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facts Report.
        /// </summary>
        internal static string repPersonFactsByChapter {
            get {
                return ResourceManager.GetString("repPersonFactsByChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Report.
        /// </summary>
        internal static string repPersonOnlineDataByChapter {
            get {
                return ResourceManager.GetString("repPersonOnlineDataByChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string restoreItem {
            get {
                return ResourceManager.GetString("restoreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic Archive Platform.
        /// </summary>
        internal static string sap {
            get {
                return ResourceManager.GetString("sap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by sources.
        /// </summary>
        internal static string searchBySource {
            get {
                return ResourceManager.GetString("searchBySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search checks.
        /// </summary>
        internal static string SearchChecks {
            get {
                return ResourceManager.GetString("SearchChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search inquiry.
        /// </summary>
        internal static string SearchInq {
            get {
                return ResourceManager.GetString("SearchInq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        internal static string searchResults {
            get {
                return ResourceManager.GetString("searchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with the synonyms.
        /// </summary>
        internal static string Searchwiththesynonyms {
            get {
                return ResourceManager.GetString("Searchwiththesynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select working area parameters.
        /// </summary>
        internal static string selWorkArea {
            get {
                return ResourceManager.GetString("selWorkArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic archive.
        /// </summary>
        internal static string semanticArchive {
            get {
                return ResourceManager.GetString("semanticArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic scheme.
        /// </summary>
        internal static string SemanticConnection {
            get {
                return ResourceManager.GetString("SemanticConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic network.
        /// </summary>
        internal static string semanticnet {
            get {
                return ResourceManager.GetString("semanticnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic layout.
        /// </summary>
        internal static string SemNet_AutoTabName {
            get {
                return ResourceManager.GetString("SemNet_AutoTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server message.
        /// </summary>
        internal static string serverMessage {
            get {
                return ResourceManager.GetString("serverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstration.
        /// </summary>
        internal static string shareDashboard {
            get {
                return ResourceManager.GetString("shareDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Than Discovery.
        /// </summary>
        internal static string slogan {
            get {
                return ResourceManager.GetString("slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service modules.
        /// </summary>
        internal static string sm {
            get {
                return ResourceManager.GetString("sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soon.
        /// </summary>
        internal static string soon {
            get {
                return ResourceManager.GetString("soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source data.
        /// </summary>
        internal static string SourceData {
            get {
                return ResourceManager.GetString("SourceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network structure.
        /// </summary>
        internal static string strnet {
            get {
                return ResourceManager.GetString("strnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        internal static string tc {
            get {
                return ResourceManager.GetString("tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string TitleLinks {
            get {
                return ResourceManager.GetString("TitleLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        internal static string TitleTranslate {
            get {
                return ResourceManager.GetString("TitleTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to design.
        /// </summary>
        internal static string toedit {
            get {
                return ResourceManager.GetString("toedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to cart.
        /// </summary>
        internal static string toolsAddToCart {
            get {
                return ResourceManager.GetString("toolsAddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to Cart.
        /// </summary>
        internal static string toolsGoToCart {
            get {
                return ResourceManager.GetString("toolsGoToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to original document.
        /// </summary>
        internal static string toolsShowOriginalDoc {
            get {
                return ResourceManager.GetString("toolsShowOriginalDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whole view.
        /// </summary>
        internal static string toolsToFullView {
            get {
                return ResourceManager.GetString("toolsToFullView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to original text.
        /// </summary>
        internal static string toolsToOriginalText {
            get {
                return ResourceManager.GetString("toolsToOriginalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to short view.
        /// </summary>
        internal static string toolsToShortView {
            get {
                return ResourceManager.GetString("toolsToShortView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translate.
        /// </summary>
        internal static string toolsTranslate {
            get {
                return ResourceManager.GetString("toolsTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translate.
        /// </summary>
        internal static string translate {
            get {
                return ResourceManager.GetString("translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        internal static string tree {
            get {
                return ResourceManager.GetString("tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types tree.
        /// </summary>
        internal static string treeТypes {
            get {
                return ResourceManager.GetString("treeТypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of content.
        /// </summary>
        internal static string typeContent {
            get {
                return ResourceManager.GetString("typeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        internal static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file name is invalid..
        /// </summary>
        internal static string UploadedImageInvalidFileName {
            get {
                return ResourceManager.GetString("UploadedImageInvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded image has invalid file type.
        /// </summary>
        internal static string UploadedImageInvalidFormat {
            get {
                return ResourceManager.GetString("UploadedImageInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of image shouldn&apos;t be more than 50 MB.
        /// </summary>
        internal static string UploadedImageSizeConstraint {
            get {
                return ResourceManager.GetString("UploadedImageSizeConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options for display.
        /// </summary>
        internal static string variantView {
            get {
                return ResourceManager.GetString("variantView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view description.
        /// </summary>
        internal static string viewadescription {
            get {
                return ResourceManager.GetString("viewadescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working group.
        /// </summary>
        internal static string WorkGroup {
            get {
                return ResourceManager.GetString("WorkGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working groups.
        /// </summary>
        internal static string workGroups {
            get {
                return ResourceManager.GetString("workGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of birth.
        /// </summary>
        internal static string Yearofbirth {
            get {
                return ResourceManager.GetString("Yearofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login.
        /// </summary>
        internal static string Youlogin {
            get {
                return ResourceManager.GetString("Youlogin", resourceCulture);
            }
        }
    }
}
